Class %ZEN.Report.DataCache Extends %RegisteredObject [ Deprecated, System = 4 ]
{

Property globalindex As %Integer;

Property counter As %ZEN.Report.RecordCounter;

Property saveCounter As %Integer;

Property saveArray [ MultiDimensional ];

Property atEnd [ InitialExpression = 0 ];

Property AtEndValues [ MultiDimensional ];

Property AtEndValue;

Method %unfetch()
{
}

Method %fetch()
{
}

Method %save()
{
}

Method %restore()
{
}

Method %put(pLevel As %Integer, n As %Integer)
{
}

Method %set(n As %Integer)
{
}

Method %get(pLevel As %Integer, n As %Integer) As %Integer
{
}

Method %atEnd() As %Boolean
{
}

}
