/// <Class>bookmarkTitle</Class>
/// The bookmarkTitle formatting object is used to identify, in human readable form, an access point.<br/>
/// The children of the bookmarkTitle when rendered are the human readable form
Class %ZEN.Report.Display.bookmarkTitle Extends childrenNode [ Deprecated ]
{

/// This internal method generates the xsl-fo of the children of bookmarkTitle
Method %DrawToXSLFO(ByRef context As %String, ByRef XSL As %GlobalCharacterStream, delay As %GlobalCharacterStream) As %Status
{
}

}
