Class %Compiler.iFind.Index [ Abstract, System = 2 ]
{

ClassMethod GenerateGlobalNames(pClass As %String(MAXLEN=""), pIndex As %String(MAXLEN=""))
{
}

ClassMethod GetDataGlobalAndColumn(pClass As %String(MAXLEN=""), pIndex As %String(MAXLEN=""), ByRef pFetchCode As %String(MAXLEN="") = "", ByRef pStreamLoc As %String(MAXLEN="") = "", ByRef pCalcCode As %String(MAXLEN=""), ByRef pType As %String(MAXLEN="") = "")
{
}

ClassMethod GetGlobalForAppend(pClass, pIndex, pGlobal) As %String(MAXLEN="")
{
}

}
