/// This class is used internally by InterSystems IRIS. You should not make direct use of it within your applications. There is no guarantee made about either the behavior or future operation of this class.
/// <p>Simple HTML-based meter that displays a value as a bar.
Class %CSP.Util.HTMLBarMeter Extends %CSP.Util.HTMLMeter [ ServerOnly = 1, System = 4 ]
{

/// Draw the style section of this HTML meter
ClassMethod OnHTMLStyle()
{
}

/// Draw the script section of this HTML meter
ClassMethod OnHTMLScript()
{
}

/// Draw the body of this HTML meter
Method OnHTMLBody()
{
}

}
