/// This class is used internally by InterSystems IRIS.
/// You should not make direct use of it within your applications.
/// There is no guarantee made about either the behavior or future operation of this class.<p>
///
/// The <b>%CSP.RuleDescription</b> class represents the csr:description tag within the DOM model for a CSR page.
Class %CSP.RuleDescription Extends %CSP.RuleElement [ Not ProcedureBlock, System = 3 ]
{

/// Save description of rule.
Method RenderStartTag() As %Status [ Internal ]
{
}

}
