Class %SYSTEM.Dictionary Extends Help [ Abstract, Not ProcedureBlock, System = 4 ]
{

ClassMethod defClassDefined(%class) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassKeyDefined(%class, %ckey) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassArrayDefined(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod defMemberDefined(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod defMemberKeyDefined(%class, %ckey, %member, %mkey) As %String [ CodeMode = expression ]
{
}

ClassMethod defSubMemberDefined(%class, %ckey, %member, %mkey, %submember) As %String [ CodeMode = expression ]
{
}

ClassMethod defSubMemberKeyDefined(%class, %ckey, %member, %mkey, %submember, %skey) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassKeyGet(%class, %ckey) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassArrayGet(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod defMemberKeyGet(%class, %ckey, %member, %mkey) As %String [ CodeMode = expression ]
{
}

ClassMethod defMemberArrayGet(%class, %ckey, %member, %mkey, %msub) As %String [ CodeMode = expression ]
{
}

ClassMethod defSubMemberKeyGet(%class, %ckey, %member, %mkey, %submember, %skey) As %String [ CodeMode = expression ]
{
}

ClassMethod defSubMemberArrayGet(%class, %ckey, %member, %mkey, %submember, %skey, %ssub) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassKill(%class)
{
}

ClassMethod defClassKeyKill(%class, %ckey)
{
}

ClassMethod defClassArrayKill(%class, %ckey, %member)
{
}

ClassMethod defMemberKill(%class, %ckey, %member)
{
}

ClassMethod defMemberKeyKill(%class, %ckey, %member, %mkey)
{
}

ClassMethod defSubMemberKill(%class, %ckey, %member, %mkey, %submember)
{
}

ClassMethod defSubMemberKeyKill(%class, %ckey, %member, %mkey, %submember, %skey)
{
}

ClassMethod defClassNext(%class) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassKeyNext(%class, %ckey) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassArrayNext(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod defMemberNext(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod defMemberKeyNext(%class, %ckey, %member, %mkey) As %String [ CodeMode = expression ]
{
}

ClassMethod defSubMemberNext(%class, %ckey, %member, %mkey, %submember) As %String [ CodeMode = expression ]
{
}

ClassMethod defSubMemberKeyNext(%class, %ckey, %member, %mkey, %submember, %skey) As %String [ CodeMode = expression ]
{
}

ClassMethod defClassSet(%class, %value)
{
}

ClassMethod defClassKeySet(%class, %ckey, %value)
{
}

ClassMethod defClassArraySet(%class, %ckey, %member, %value)
{
}

ClassMethod defMemberSet(%class, %ckey, %member, %value)
{
}

ClassMethod defMemberKeySet(%class, %ckey, %member, %mkey, %value)
{
}

ClassMethod defMemberArraySet(%class, %ckey, %member, %mkey, %msub, %value)
{
}

ClassMethod defSubMemberSet(%class, %ckey, %member, %mkey, %submember, %value)
{
}

ClassMethod defSubMemberKeySet(%class, %ckey, %member, %mkey, %submember, %skey, %value)
{
}

ClassMethod defSubMemberArraySet(%class, %ckey, %member, %mkey, %submember, %skey, %ssub, %value)
{
}

ClassMethod comClassDefined(%class) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassKeyDefined(%class, %ckey) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassArrayDefined(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod comMemberDefined(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod comMemberKeyDefined(%class, %ckey, %member, %mkey) As %String [ CodeMode = expression ]
{
}

ClassMethod comSubMemberDefined(%class, %ckey, %member, %mkey, %submember) As %String [ CodeMode = expression ]
{
}

ClassMethod comSubMemberKeyDefined(%class, %ckey, %member, %mkey, %submember, %skey) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassKeyGet(%class, %ckey) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassArrayGet(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod comMemberKeyGet(%class, %ckey, %member, %mkey) As %String [ CodeMode = expression ]
{
}

ClassMethod comMemberArrayGet(%class, %ckey, %member, %mkey, %msub) As %String [ CodeMode = expression ]
{
}

ClassMethod comSubMemberKeyGet(%class, %ckey, %member, %mkey, %submember, %skey) As %String [ CodeMode = expression ]
{
}

ClassMethod comSubMemberArrayGet(%class, %ckey, %member, %mkey, %submember, %skey, %ssub) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassKeyGetLvar(%lvar, %class, %ckey)
{
}

ClassMethod comClassArrayGetLvar(%lvar, %class, %ckey, %member)
{
}

ClassMethod comMemberKeyGetLvar(%lvar, %class, %ckey, %member, %mkey)
{
}

ClassMethod comMemberArrayGetLvar(%lvar, %class, %ckey, %member, %mkey, %msub)
{
}

ClassMethod comSubMemberKeyGetLvar(%lvar, %class, %ckey, %member, %mkey, %submember, %skey)
{
}

ClassMethod comSubMemberArrayGetLvar(%lvar, %class, %ckey, %member, %mkey, %submember, %skey, %ssub)
{
}

ClassMethod comClassKill(%class)
{
}

ClassMethod comClassKeyKill(%class, %ckey)
{
}

ClassMethod comClassArrayKill(%class, %ckey, %member)
{
}

ClassMethod comMemberKill(%class, %ckey, %member)
{
}

ClassMethod comMemberKeyKill(%class, %ckey, %member, %mkey)
{
}

ClassMethod comSubMemberKill(%class, %ckey, %member, %mkey, %submember)
{
}

ClassMethod comSubMemberKeyKill(%class, %ckey, %member, %mkey, %submember, %skey)
{
}

ClassMethod comClassNext(%class) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassKeyNext(%class, %ckey) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassArrayNext(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod comMemberNext(%class, %ckey, %member) As %String [ CodeMode = expression ]
{
}

ClassMethod comMemberKeyNext(%class, %ckey, %member, %mkey) As %String [ CodeMode = expression ]
{
}

ClassMethod comSubMemberNext(%class, %ckey, %member, %mkey, %submember) As %String [ CodeMode = expression ]
{
}

ClassMethod comSubMemberKeyNext(%class, %ckey, %member, %mkey, %submember, %skey) As %String [ CodeMode = expression ]
{
}

ClassMethod comClassSet(%class, %value)
{
}

ClassMethod comClassKeySet(%class, %ckey, %value)
{
}

ClassMethod comClassArraySet(%class, %ckey, %member, %value)
{
}

ClassMethod comMemberSet(%class, %ckey, %member, %value)
{
}

ClassMethod comMemberKeySet(%class, %ckey, %member, %mkey, %value)
{
}

ClassMethod comSubMemberSet(%class, %ckey, %member, %mkey, %submember, %value)
{
}

ClassMethod comSubMemberKeySet(%class, %ckey, %member, %mkey, %submember, %skey, %value)
{
}

ClassMethod defStorageSubMemberDefined(%class, %ck, %m, %mk, %sm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubMemberKeyDefined(%class, %ck, %m, %mk, %sm, %sk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubMemberDefined(%class, %ck, %m, %mk, %sm, %sk, %ssm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubMemberKeyDefine(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubSubMemberDefine(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubSubMemberKeyDef(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubMemberGet(%class, %ck, %m, %mk, %sm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubMemberGet(%class, %ck, %m, %mk, %sm, %sk, %ssm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubSubMemberGet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubMemberKeyGet(%class, %ck, %m, %mk, %sm, %sk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubMemberKeyGet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubSubMemberKeyGet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubMemberKill(%class, %ck, %m, %mk, %sm)
{
}

ClassMethod defStorageSubMemberKeyKill(%class, %ck, %m, %mk, %sm, %sk)
{
}

ClassMethod defStorageSubSubMemberKill(%class, %ck, %m, %mk, %sm, %sk, %ssm)
{
}

ClassMethod defStorageSubSubMemberKeyKill(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk)
{
}

ClassMethod defStorageSubSubSubMemberKill(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm)
{
}

ClassMethod defStorageSubSubSubMemberKeyKil(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk)
{
}

ClassMethod defStorageSubMemberNext(%class, %ck, %m, %mk, %sm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubMemberKeyNext(%class, %ck, %m, %mk, %sm, %sk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubMemberNext(%class, %ck, %m, %mk, %sm, %sk, %ssm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubMemberKeyNext(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubSubMemberNext(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubSubSubMemberKeyNex(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk) As %String [ CodeMode = expression ]
{
}

ClassMethod defStorageSubMemberSet(%class, %ck, %m, %mk, %sm, %value)
{
}

ClassMethod defStorageSubMemberKeySet(%class, %ck, %m, %mk, %sm, %sk, %value)
{
}

ClassMethod defStorageSubSubMemberSet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %value)
{
}

ClassMethod defStorageSubSubMemberKeySet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %value)
{
}

ClassMethod defStorageSubSubSubMemberSet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %value)
{
}

ClassMethod defStorageSubSubSubMemberKeySet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk, %value)
{
}

ClassMethod comStorageSubMemberDefined(%class, %ck, %m, %mk, %sm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubMemberKeyDefined(%class, %ck, %m, %mk, %sm, %sk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubMemberDefined(%class, %ck, %m, %mk, %sm, %sk, %ssm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubMemberKeyDefine(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubSubMemberDefine(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubSubMemberKeyDef(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubMemberGet(%class, %ck, %m, %mk, %sm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubMemberGet(%class, %ck, %m, %mk, %sm, %sk, %ssm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubSubMemberGet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubMemberKeyGet(%class, %ck, %m, %mk, %sm, %sk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubMemberKeyGet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubSubMemberKeyGet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubMemberKill(%class, %ck, %m, %mk, %sm)
{
}

ClassMethod comStorageSubMemberKeyKill(%class, %ck, %m, %mk, %sm, %sk)
{
}

ClassMethod comStorageSubSubMemberKill(%class, %ck, %m, %mk, %sm, %sk, %ssm)
{
}

ClassMethod comStorageSubSubMemberKeyKill(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk)
{
}

ClassMethod comStorageSubSubSubMemberKill(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm)
{
}

ClassMethod comStorageSubSubSubMemberKeyKil(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk)
{
}

ClassMethod comStorageSubMemberNext(%class, %ck, %m, %mk, %sm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubMemberKeyNext(%class, %ck, %m, %mk, %sm, %sk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubMemberNext(%class, %ck, %m, %mk, %sm, %sk, %ssm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubMemberKeyNext(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubSubMemberNext(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubSubSubMemberKeyNex(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk) As %String [ CodeMode = expression ]
{
}

ClassMethod comStorageSubMemberSet(%class, %ck, %m, %mk, %sm, %value)
{
}

ClassMethod comStorageSubMemberKeySet(%class, %ck, %m, %mk, %sm, %sk, %value)
{
}

ClassMethod comStorageSubSubMemberSet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %value)
{
}

ClassMethod comStorageSubSubMemberKeySet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %value)
{
}

ClassMethod comStorageSubSubSubMemberSet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %value)
{
}

ClassMethod comStorageSubSubSubMemberKeySet(%class, %ck, %m, %mk, %sm, %sk, %ssm, %ssk, %sssm, %sssk, %value)
{
}

}
