/// This class is used internally by InterSystems IRIS. You should not make direct use of it within your applications. There is no guarantee made about either the behavior or future operation of this class.
/// <p>This pane displays text file content.
Class %CSP.UI.System.ViewTextFilePane Extends %CSP.Util.Pane [ System = 4 ]
{

/// Display content of the file
Method DrawBODY(pInstance As PageInstance) As %Status
{
}

Method DrawLogContent(filename As %String)
{
}

/// Draw javascript functions for search
Method DrawHEAD(pInstance As PageInstance) As %Status
{
}

}
