Class %DotNet.Utils Extends %RegisteredObject [ System = 4 ]
{

ClassMethod Classes(Output pStream As %GlobalCharacterStream) As %Status
{
}

ClassMethod Namespaces(Output pStream As %GlobalCharacterStream) As %Status
{
}

ClassMethod DerivedClasses(pClassName As %String, Output pStream As %GlobalCharacterStream) As %Status
{
}

ClassMethod Configuration(Output pString As %String) As %Status
{
}

ClassMethod Test()
{
}

}
