Class %DeepSee.PMML.Utils.DeepSee [ System = 4 ]
{

ClassMethod GetFactPropertyForSpec(pCubeName As %String, pSpec As %String, pAsSQL As %Boolean = 0, Output pExpression As %String) As %Status [ Internal ]
{
}

ClassMethod RunModelForListing(pCubeName As %String, pSourceObjectId As %Integer, pDefinitionClass As %String, pModelName As %String = "", pFeature As %String = "predictedValue") As %String [ SqlProc ]
{
}

}
